### PR TITLE
added new page that links to Discord Server

### LINKED ISSUE #383: Add /discord page
which just redirects to a permanent invite to the hack discord so that we don't have to tell people to go to discord.gg/lksdjflskdjflksdjfhlsdghslkdjflskdfjlksendmysufferingdjflkdfjlskdjfsldkjflskdfjsldkjfsdf

### PR DESCRIPTION
**Pull request by lilliangonick**
# Changes
Added a new page on the ButtonBar. The "Discord" button links directly to the Discord permalink. 

## Type of change
New feature

# Related Issues
close #383

### CODE REVIEW

**Comment by nathanzzhang** [comment]
Nice change! However, I think it looks a bit out of place on the nav bar tbh. I think it might need some more discussion. Regardless, good job!

**Comment by katelynsyu** [comment]
> Nice change! However, I think it looks a bit out of place on the nav bar tbh. I think it might need some more discussion. Regardless, good job!

@nathanzzhang @jakobreinwald @maggieelli @jamesmwu 
Do you think it would be better if we changed the the text that appears in the nav bar to "Contact (Us)" or something like that?

**Comment by jamesmwu** [comment]
I think that having the text on the nav bar as "Discord" is fine-- I feel like Contact Us implies email usually. And while it's not typical, I think having the link directly on the nav bar is fine since it's our club's main way of communication and up to date information.

**Comment by maggieelli** [comment]
I kind of agree with Katelyn that "Discord" is a bit odd to have on our nav bar since it feels out of place compared to the other pages, but I get why we want to have the Discord link more accessible. Personally I think at least changing the text to "Join Us" or something would be much better, but also I think it still is a bit odd to have it on the nav bar since it's not directing to a page, but rather a link.

Do we think the glowy gradient link on our home page under our banner that says "Want to learn more about our internship program..." is necessary to have right now? If not, we could replace that button to something like "Join our Discord to get up-to-date information about our events!" or something

**Comment by nathanzzhang** [comment]
I actually like the idea of replacing the glowy gradient with a link to our discord with some relevant text instead of adding it to the navbar. Although with that change, the button about half a page down "Join the ACM Hack Discord" is a bit irrelevant LOL

**Comment by katelynsyu** [comment]
Guys lets just nix the discord link in the nav bar entirely and just create a page `hack.uclaacm.com/discord` that links to the discord so we can tell people to go there (it's an easier link to remember and type)

**Review by jamesmwu — CHANGES_REQUESTED** [review]
Could you remove the current link as it is and instead change the "Apply" button to say "Discord" and link to the Discord?

**Pull request closed without merging**
