### PR TITLE
Updated Team Page

### PR DESCRIPTION
**Pull request by khxia**
# Changes
* Removed images and descriptions of seniors.
* Updated existing officers' bios and images if needed.

### CODE REVIEW

**Review by jodymlin — APPROVED** [review]
lgtm :+1:

**Review by TimothyGu — COMMENTED** [review]
wow @euglo no longer looks like he's in HS

also is Jamie no longer doing advisor?

**Comment by khxia** [comment]
Just contacted her and she is still doing Hack

**Comment by euglo** [comment]
@TimothyGu smh

also yes @khxia , jamie is considered an advisor as of this year

**Pull request merged**
