### PR TITLE
Add Winter Events

### LINKED ISSUE #352: Change events page
* update HackEvents with banner and blurb
* update upcoming events

### PR DESCRIPTION
**Pull request by katelynsyu**
# Changes

Add StackSchool and HOTH to event page.

## Type of change

Please delete options that are not relevant.

- [x] Content Update (non-breaking change which updates the content of the website)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Related Issues

Fixes #352

### CODE REVIEW

**Comment by katelynsyu** [comment]
Ok we need this stuff up but I'll come back soon to this because a few things need to be updated
- Facebook link to Stackschool in event cards
- HOTH banner needs to be updated
- HOTH event card needs to be added when we know when (date and time) and where it's happening

**Review by nathanzzhang — APPROVED** [review]
lgtm!

**Review by jamesmwu — APPROVED** [review]
Looks good!

**Review by maggieelli — APPROVED** [review]
LGTM!

**Pull request merged**
