### PR TITLE
Added Katelyn/James as contributors

### LINKED ISSUE #361: update README with contributors
add Katelyn and James to Readme as contributors

### PR DESCRIPTION
**Pull request by jamesmwu**
Fixes #361

### CODE REVIEW

**Comment by katelynsyu** [comment]
Can we split the contributors into current contributors and past contributors like on the HOTH website?

**Comment by jamesmwu** [comment]
> Can we split the contributors into current contributors and past contributors like on the HOTH website?

yes

**Comment by katelynsyu** [comment]
Tbh, I dont think we have enough people to split contributors into 2 lists. just put our names at the back

**Review by katelynsyu — APPROVED** [review]
LGTM :)

**Pull request merged**
