### PR TITLE
Add running StackSchool data to archive

### PR DESCRIPTION
**Pull request by nareha**
# Changes

Added current StackSchool data onto the archive, in line with wanting to turn archive into a "running" archive.

## Type of change

- [X] Content Update (non-breaking change which updates the content of the website)

# Related Issues

#371

### CODE REVIEW

**Comment by nareha** [comment]
Requesting StackSchool directors for content review (tags, correct information, etc.).

**Review by nathanzzhang — APPROVED** [review]
yay lgtm!

**Review by jamesmwu — APPROVED** [review]
Looks good!

**Review by katelynsyu — APPROVED** [review]
LGTM!!!

**Pull request merged**
