### PR TITLE
easter egg for profile picture

### PR DESCRIPTION
**Pull request by GalenWong**
<strike> Waiting on Alex and Raji's picture. </strike> Issue #95

### CODE REVIEW

**Comment by malsf21** [comment]
I would just like to comment that this is a hilarious feature. That is all 🚀

**Comment by TimothyGu** [comment]
@khxia @RajeshwariJadhav ping

**Review by jodymlin — CHANGES_REQUESTED** [review]
On my laptop, Kristie's photo gets cut off
image
Could we recrop it so her face is in it? 

Also was swapping connie and lea's photo intentional? If so, I like it. If not, leave it :D

**Comment by GalenWong** [comment]
> On my laptop, Kristie's photo gets cut off

interesting, kristie is in frame on mine. Don't know why CSS is different on both.

> Also was swapping connie and lea's photo intentional? If so, I like it. If not, leave it :D

it was their intention...

**Review by jodymlin — APPROVED** [review]
Looks good to me :)

**Pull request merged**
