### PR TITLE
Update Workshop Archive

### LINKED ISSUE #377: update workshop archive
- add the remaining sessions of stackschool
- change hoth 9 to hack **on** the hill
- add the hoth X workshops

### PR DESCRIPTION
**Pull request by jamesmwu**
# Changes

Added remaining stackschool sessions, changed hoth9 to say 'Hack on the Hill' instead of 'Hack off the Hill', and added hoth X workshops

## Type of change

Please delete options that are not relevant.

- [x] Content Update (non-breaking change which updates the content of the website)

# Related Issues

Fixes #377

### CODE REVIEW

**Review by nathanzzhang — CHANGES_REQUESTED** [review]
lgtm, but need to resolve merge conflict rip

**Review by nathanzzhang — APPROVED** [review]
lgtm!

**Review by ariyin — APPROVED** [review]
looks legit
i trust the judgement of nathan and maggie 👍

**Review by katelynsyu — APPROVED** [review]
LGTM! Looks like there’s a but that makes the “Taught by” text render with the wrong styling in safari (iPhone, horizontal) but we can address that later :)

**Pull request merged**
